clear; clc; close all;
SAVE_PDF = false;
CLOSE_AFTER_SAVE = false;
script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end
cd(script_dir);
required_files = { ...
    'simulation_engine.m', ...
    'sampling_certificate.m'};
for kk = 1:numel(required_files)
    f = fullfile(script_dir,required_files{kk});
    if exist(f,'file') ~= 2
        error('Required file not found: %s',f);
    end
end
outdir = fullfile(script_dir,'..','data');
if exist(outdir,'dir') ~= 7
    mkdir(outdir);
end
if exist(fullfile(script_dir,'results'),'dir') ~= 7
    mkdir(fullfile(script_dir,'results'));
end
fprintf('\n============================================================\n');
fprintf('CONSISTENT SAMPLING SWEEP\n');
fprintf('============================================================\n');
fprintf('Simulation engine:\n%s\n\n', ...
    which('simulation_engine.m'));
fprintf('Certificate script:\n%s\n\n', ...
    which('sampling_certificate.m'));
Nmc  = 100;
hEM  = 1e-5;
Tsim = 1.5;
seed = 1;
Aaper = 0.4;
sigma1 = 1e-4;
sigma0 = 5e-6;
duty = 0.75;
noise = 0.2;
pins = 4;
gain = 26;
topology = 1;
qh = 0;
hs_list = [ ...
    1e-5, ...
    5e-5, ...
    1e-4, ...
    5e-4, ...
    1e-3, ...
    5e-3, ...
    1e-2, ...
    2e-2, ...
    5e-2, ...
    1e-1];
Ncase = numel(hs_list);
case_names = cell(1,Ncase);
case_par   = zeros(Ncase,12);
for k = 1:Ncase
    hs = hs_list(k);
    case_names{k} = sprintf('hs_%g',hs);
    case_par(k,:) = [ ...
        3, ...
        2, ...
        hs, ...
        sigma1, ...
        sigma0, ...
        duty, ...
        noise, ...
        pins, ...
        gain, ...
        topology, ...
        qh, ...
        Aaper];
end
fprintf('Running %d sampling-period cases with Nmc = %d...\n\n', ...
    Ncase,Nmc);
run(fullfile(script_dir,'simulation_engine.m'));
if ~exist('all_metrics','var')
    error('simulation_engine.m did not create all_metrics.');
end
save(fullfile(outdir,'sampling_consistent_results.mat'), ...
    'all_metrics', ...
    'case_names', ...
    'case_par', ...
    'hs_list', ...
    'Nmc', ...
    'hEM', ...
    'Tsim', ...
    'seed', ...
    'schedule_records', ...
    'curves', ...
    'curve_time', ...
    'state_example', ...
    'event_example');
result_prefix = 'sampling_consistent';
run(fullfile(script_dir,'sampling_certificate.m'));
cert_src = fullfile( ...
    script_dir, ...
    'results', ...
    'sampling_consistent_certificates.csv');
cert_dst = fullfile( ...
    outdir, ...
    'sampling_consistent_certificates.csv');
if exist(cert_src,'file') ~= 2
    error('Certificate file was not generated: %s',cert_src);
end
copyfile(cert_src,cert_dst,'f');
C = readtable(cert_dst,'VariableNamingRule','preserve');
hcert = C.h_certified_limit(1);
fprintf('\nCertified sufficient sampling limit:\n');
fprintf('h_cert = %.12g s\n\n',hcert);
if Nmc == 100
    tcrit = 1.98421695150868;
else
    tcrit = 1.96;
end
Nu   = zeros(Ncase,1);
Nulo = zeros(Ncase,1);
Nuhi = zeros(Ncase,1);
J    = zeros(Ncase,1);
Jlo  = zeros(Ncase,1);
Jhi  = zeros(Ncase,1);
E    = zeros(Ncase,1);
Elo  = zeros(Ncase,1);
Ehi  = zeros(Ncase,1);
tail_mean = zeros(Ncase,1);
final_error_max = zeros(Ncase,1);
pathwise_max_error_max = zeros(Ncase,1);
active_fraction = zeros(Ncase,1);
sensing_instants = zeros(Ncase,1);
sampling_ok = false(Ncase,1);
for k = 1:Ncase
    x = all_metrics(:,1,k);
    Nu(k) = mean(x);
    hw = tcrit*std(x,0)/sqrt(Nmc);
    Nulo(k) = Nu(k)-hw;
    Nuhi(k) = Nu(k)+hw;
    x = all_metrics(:,2,k);
    J(k) = mean(x);
    hw = tcrit*std(x,0)/sqrt(Nmc);
    Jlo(k) = J(k)-hw;
    Jhi(k) = J(k)+hw;
    x = all_metrics(:,3,k);
    E(k) = mean(x);
    hw = tcrit*std(x,0)/sqrt(Nmc);
    Elo(k) = E(k)-hw;
    Ehi(k) = E(k)+hw;
    tail_mean(k) = mean(all_metrics(:,4,k));
    final_error_max(k) = ...
        max(all_metrics(:,5,k));
    pathwise_max_error_max(k) = ...
        max(all_metrics(:,6,k));
    active_fraction(k) = ...
        mean(all_metrics(:,8,k));
    sensing_instants(k) = ...
        mean(all_metrics(:,9,k));
    sampling_ok(k) = hs_list(k) < hcert;
end
hs_col = hs_list(:);
hs_over_hcert = hs_col ./ hcert;
idx_base = find(abs(hs_col-5e-5)<1e-14,1);
if isempty(idx_base)
    error('Cannot find baseline h_s = 5e-5 case.');
end
B = schedule_records{idx_base};
if isempty(B) || size(B,2) < 3
    error('Unexpected schedule_records format.');
end
active_widths = B(:,2)-B(:,1);
h_active_max = max(active_widths);
fprintf('Maximum active-window width = %.12g s\n\n', ...
    h_active_max);
summary_file = fullfile( ...
    outdir, ...
    'sampling_consistent_summary.csv');
fid = fopen(summary_file,'w');
fprintf(fid,[ ...
    'hs,' ...
    'updates_mean,updates_ci_low,updates_ci_high,' ...
    'J_mean,J_ci_low,J_ci_high,' ...
    'E_mean,E_ci_low,E_ci_high,' ...
    'tail_mean,' ...
    'final_error_max,' ...
    'pathwise_max_error_max,' ...
    'h_certified_limit,' ...
    'hs_over_hcert,' ...
    'sampling_ok,' ...
    'active_fraction,' ...
    'sensing_instants\n']);
for k = 1:Ncase
    fprintf(fid,[ ...
        '%.12g,' ...
        '%.12g,%.12g,%.12g,' ...
        '%.12g,%.12g,%.12g,' ...
        '%.12g,%.12g,%.12g,' ...
        '%.12g,' ...
        '%.12g,' ...
        '%.12g,' ...
        '%.12g,' ...
        '%.12g,' ...
        '%d,' ...
        '%.12g,' ...
        '%.12g\n'], ...
        hs_col(k), ...
        Nu(k),Nulo(k),Nuhi(k), ...
        J(k),Jlo(k),Jhi(k), ...
        E(k),Elo(k),Ehi(k), ...
        tail_mean(k), ...
        final_error_max(k), ...
        pathwise_max_error_max(k), ...
        hcert, ...
        hs_over_hcert(k), ...
        sampling_ok(k), ...
        active_fraction(k), ...
        sensing_instants(k));
end
fclose(fid);
fprintf('\n');
fprintf('====================================================================================================================\n');
fprintf('TABLE 7 PREVIEW -- CONSISTENT BROWNIAN PATHS\n');
fprintf('====================================================================================================================\n');
fprintf('%-10s %-9s %-8s %-27s %-30s %-30s\n', ...
    'h_s', ...
    'h_s/hc', ...
    'Cert.', ...
    'N_u [95%% CI]', ...
    'J_varrho [95%% CI]', ...
    'J_u [95%% CI]');
for k = 1:Ncase
    if sampling_ok(k)
        cert_text = 'Yes';
    else
        cert_text = 'No';
    end
    fprintf([ ...
        '%-10.1e ' ...
        '%-9.2f ' ...
        '%-8s ' ...
        '%7.2f [%7.2f,%7.2f]   ' ...
        '%.6f [%.6f,%.6f]   ' ...
        '%.4f [%.4f,%.4f]\n'], ...
        hs_col(k), ...
        hs_over_hcert(k), ...
        cert_text, ...
        Nu(k),Nulo(k),Nuhi(k), ...
        J(k),Jlo(k),Jhi(k), ...
        E(k),Elo(k),Ehi(k));
end
fprintf('====================================================================================================================\n');
fprintf('\nBASELINE CONSISTENCY CHECK\n');
fprintf('--------------------------\n');
fprintf('h_s = %.1e\n',hs_col(idx_base));
fprintf('Nu = %.8f\n',Nu(idx_base));
fprintf('J  = %.10f\n',J(idx_base));
fprintf('E  = %.10f\n',E(idx_base));
fprintf('Active fraction = %.10f\n', ...
    active_fraction(idx_base));
fprintf('Sensing instants = %.10f\n', ...
    sensing_instants(idx_base));
fprintf('\nExpected main-batch values:\n');
fprintf('Nu = 372.28000000\n');
fprintf('J  = 0.0465761382\n');
fprintf('E  = 7.1970799158\n');
fprintf('\nDifferences from main baseline:\n');
fprintf('Delta Nu = %.12g\n', ...
    Nu(idx_base)-372.28);
fprintf('Delta J  = %.12g\n', ...
    J(idx_base)-0.0465761382);
fprintf('Delta E  = %.12g\n', ...
    E(idx_base)-7.1970799158);
set(0,'DefaultAxesFontName','Times New Roman');
set(0,'DefaultTextFontName','Times New Roman');
AXIS_FS   = 14;
LABEL_FS  = 17;
TITLE_FS  = 14;
LEGEND_FS = 11;
fig = figure('Color','w');
set(fig, ...
    'Units','centimeters', ...
    'Position',[2 2 40 15]);
tl = tiledlayout( ...
    fig,1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');
ax1 = nexttile(tl,1);
hold(ax1,'on');
hJ = errorbar( ...
    ax1, ...
    hs_col,J,J-Jlo,Jhi-J, ...
    'o-', ...
    'LineWidth',1.8, ...
    'MarkerSize',7, ...
    'MarkerFaceColor','w', ...
    'CapSize',8);
hCert1 = xline( ...
    ax1, ...
    hcert, ...
    '--', ...
    'LineWidth',1.5);
hRef = yline( ...
    ax1, ...
    0.05, ...
    ':', ...
    'LineWidth',1.5);
[~,idx5] = min(abs(hs_col-5e-3));
plot( ...
    ax1, ...
    hs_col(idx5), ...
    J(idx5), ...
    'o', ...
    'MarkerSize',9, ...
    'LineWidth',1.6, ...
    'HandleVisibility','off');
hRatioText = text( ...
    ax1, ...
    hs_col(idx5)*1.10, ...
    J(idx5)+0.004, ...
    sprintf('$%.2f\\,h_{\\rm cert}$', ...
    hs_over_hcert(idx5)), ...
    'Interpreter','latex', ...
    'FontSize',12, ...
    'BackgroundColor','w', ...
    'Margin',0.25);
set(ax1, ...
    'XScale','log', ...
    'FontName','Times New Roman', ...
    'FontSize',AXIS_FS, ...
    'LineWidth',1.0);
grid(ax1,'off');
box(ax1,'on');
xlabel( ...
    ax1, ...
    'Sampling period $h_s$ (s)', ...
    'Interpreter','latex', ...
    'FontSize',LABEL_FS);
ylabel( ...
    ax1, ...
    '$J_\varrho$', ...
    'Interpreter','latex', ...
    'FontSize',LABEL_FS);
title( ...
    ax1, ...
    '(a) Certified limit and tested error', ...
    'FontWeight','normal', ...
    'FontSize',TITLE_FS);
xlim(ax1,[min(hs_col)*0.8 max(hs_col)*1.25]);
ylim(ax1,[0.04 0.13]);
legend( ...
    ax1, ...
    [hJ,hCert1,hRef], ...
    { ...
    'Tested $J_\varrho$ [95\% CI]', ...
    'Certified sampling limit $h_{\rm cert}$', ...
    'Reference level $J_\varrho=0.05$' ...
    }, ...
    'Interpreter','latex', ...
    'Location','northwest', ...
    'FontSize',LEGEND_FS, ...
    'Box','on');
ax2 = nexttile(tl,2);
hold(ax2,'on');
yyaxis(ax2,'left');
hNu = errorbar( ...
    ax2, ...
    hs_col,Nu,Nu-Nulo,Nuhi-Nu, ...
    'o-', ...
    'LineWidth',1.8, ...
    'MarkerSize',7, ...
    'MarkerFaceColor','w', ...
    'CapSize',8);
ylabel( ...
    ax2, ...
    'Mean global updates $N_u$', ...
    'Interpreter','latex', ...
    'FontSize',LABEL_FS);
ylim(ax2,[0 max(Nuhi)*1.12]);
yyaxis(ax2,'right');
hE = errorbar( ...
    ax2, ...
    hs_col,E,E-Elo,Ehi-E, ...
    's--', ...
    'LineWidth',1.8, ...
    'MarkerSize',7, ...
    'MarkerFaceColor','w', ...
    'CapSize',8);
ylabel( ...
    ax2, ...
    '$J_u$', ...
    'Interpreter','latex', ...
    'FontSize',LABEL_FS);
ylim(ax2,[0 max(Ehi)*1.15]);
yyaxis(ax2,'left');
hCert2 = xline( ...
    ax2, ...
    hcert, ...
    '--', ...
    'LineWidth',1.5);
hActive = xline( ...
    ax2, ...
    h_active_max, ...
    ':', ...
    'LineWidth',1.5);
set(ax2, ...
    'XScale','log', ...
    'FontName','Times New Roman', ...
    'FontSize',AXIS_FS, ...
    'LineWidth',1.0);
grid(ax2,'off');
box(ax2,'on');
xlabel( ...
    ax2, ...
    'Sampling period $h_s$ (s)', ...
    'Interpreter','latex', ...
    'FontSize',LABEL_FS);
title( ...
    ax2, ...
    '(b) Resource trade-off', ...
    'FontWeight','normal', ...
    'FontSize',TITLE_FS);
xlim(ax2,[min(hs_col)*0.8 max(hs_col)*1.25]);
legend( ...
    ax2, ...
    [hNu,hE,hCert2,hActive], ...
    { ...
    '$N_u$', ...
    '$J_u$', ...
    'Certified sampling limit $h_{\rm cert}$', ...
    'Maximum active-window width' ...
    }, ...
    'Interpreter','latex', ...
    'Location','northwest', ...
    'FontSize',LEGEND_FS, ...
    'Box','on');
drawnow;
plotedit(fig,'on');
fprintf('\nFigure 7 preview created.\n');
fprintf('SAVE_PDF = false, so nothing has been overwritten.\n');
fprintf('You may manually adjust legends/text after verification.\n');
if SAVE_PDF
    plotedit(fig,'off');
    exportgraphics( ...
        fig, ...
        fullfile(outdir,'sampling_range_consistent.pdf'), ...
        'ContentType','vector');
    fprintf('Saved sampling_range_consistent.pdf\n');
    if CLOSE_AFTER_SAVE
        close(fig);
    end
end
fprintf('\nGenerated files:\n');
fprintf('%s\n',summary_file);
fprintf('%s\n',cert_dst);
fprintf('%s\n',fullfile(outdir,'sampling_consistent_results.mat'));
fprintf('\nCONSISTENT SAMPLING SWEEP FINISHED.\n');
