clear; clc;
script_dir=fileparts(mfilename('fullpath'));
Nmc=2; hEM=1e-5; Tsim=1e-3; seed=1;
case_names={'CP_smoke','AIPE_smoke'};
case_par=[1 1 5e-5 1e-4 5e-6 .75 .2 4 26 1 0 0; ...
          3 2 5e-5 1e-4 5e-6 .75 .2 4 26 1 0 .4];
Nstep=round(Tsim/hEM);
rng(seed,'twister');
dB_all_override=sqrt(hEM)*randn(Nstep,Nmc)';
schedule_boundaries_override=[0 .00075 .001];
run(fullfile(script_dir,'simulation_engine.m'));
assert(isequal(size(all_metrics),[Nmc,9,2]));
assert(all(isfinite(all_metrics(:))));
assert(all(all_metrics(:,1:3,:)>0,'all'));
assert(all(all_metrics(:,1,:)<=all_metrics(:,9,:),'all'));
assert(all(mod(all_metrics(:,1,:),1)==0,'all'));
assert(all(mod(all_metrics(:,9,:),1)==0,'all'));
assert(all(all_metrics(:,8,1)==1));
assert(all(abs(all_metrics(:,8,2)-.75)<1e-12));
fprintf('SMOKE_TEST_PASS Nu_CP=%.6g Nu_AIPE=%.6g\n',mean(all_metrics(:,1,1)),mean(all_metrics(:,1,2)));
